name: Release

on:
  release:
    types: [prereleased]
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"

permissions: write-all

jobs:
  build:
    strategy:
      matrix:
        goos: [windows, linux]
        goarch: [amd64]
      fail-fast: false

    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: 0
      VERSION: ${{ github.event.release.tag_name || github.sha }}

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Show workflow information
        id: get_filename
        run: |
          export _NAME="${GOOS}-${GOARCH}"
          echo "构建信息: GOOS=${GOOS}, GOARCH=${GOARCH}, 资产名称=${_NAME}"
          echo "::set-output name=ASSET_NAME::${_NAME}"
          echo "ASSET_NAME=${_NAME}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ^1.21  # 升级到更高的Go版本（gvisor推荐1.20+）
          cache: true

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get project dependencies
        run: go mod download && go mod verify

      - name: Build with gvisor tags
        run: |
          mkdir -p build_assets
          # 添加gvisor所需的构建标签，强制启用兼容模式
          go build -v -o build_assets/EasierConnect \
            -trimpath \
            -tags "gvisor,go1.21" \  # 根据Go版本添加对应的标签
            -ldflags "-s -w -buildid= -X main.version=${VERSION} -X main.commit=${GITHUB_SHA::8}" \
            .

      - name: Rename Windows executable
        if: matrix.goos == 'windows'
        run: |
          cd ./build_assets || exit 1
          mv EasierConnect EasierConnect.exe

      - name: Create ZIP archive
        run: |
          pushd build_assets || exit 1
          zip -9vr ../EasierConnect-${ASSET_NAME}.zip .
          popd || exit 1
          unzip -l EasierConnect-${ASSET_NAME}.zip

      - name: Upload release binary
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} \
            EasierConnect-${{ steps.get_filename.outputs.ASSET_NAME }}.zip \
            --clobber \
            --name "EasierConnect-${{ steps.get_filename.outputs.ASSET_NAME }}.zip"
